using System;
using System.IO;
using System.Threading.Tasks;

namespace NoiseBackendExample;

class Program
{
    static async Task Main(string[] args)
    {
        Console.WriteLine("NoiseBackendExample C# Port");
        
        // Path to the .zo file generated by Racket
        // In the Swift example, it's typically in a resource bundle.
        // Here we assume it's in the same directory or passed as an arg.
        string zoPath = "core.zo"; // Default
        if (args.Length > 0) zoPath = args[0];

        if (!File.Exists(zoPath))
        {
            Console.WriteLine($"Warning: .zo file not found at '{Path.GetFullPath(zoPath)}'.");
            Console.WriteLine("Please compile the Racket code (see Swift example Makefile) and place the .zo file here.");
            Console.WriteLine("Example usage: NoiseBackendExample.exe <path-to-core.zo>");
            // Proceeding might crash if Backend tries to load it immediately, but let's try.
        }

        try
        {
            Console.WriteLine("Initializing Backend...");
            // Matches Swift: NoiseBackend.Backend(withZo: zo, andMod: mod, andProc: proc)
            // Swift Makefile: --mods $@ ${RKT_SRC}/main.rkt
            // Mod name likely "main" or "core". The Swift example uses "main" in Makefile command potentially? 
            // In Backend.swift: init(withZo zo: URL, andMod mod: String, andProc proc: String)
            // But checking where it's called in Swift: App likely calls it.
            // Let's assume standard names "main" and "serve".
            
            var backend = new Backend(zoPath, "main", "serve");

            Console.WriteLine("Fetching Top Stories...");
            var stories = await backend.GetTopStories();
            Console.WriteLine($"Got {stories.Count} stories.");
            
            foreach (var story in stories)
            {
                Console.WriteLine($"Story: {story.Title} (ID: {story.Id})");
                Console.WriteLine($"  Fetching comments for story {story.Id}...");
                var comments = await backend.GetComments(story.Id);
                Console.WriteLine($"  Got {comments.Count} comments.");
                foreach (var comment in comments)
                {
                    Console.WriteLine($"    [{comment.Author}] {comment.Text}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }

        Console.WriteLine("Press any key to exit.");
        Console.ReadKey();
    }
}
